### ISSUE TITLE
TypeError: feature.getFailureException is not a function with version 0.1.12

### ISSUE THREAD

**Issue by martino-letgo** [itszero/wdio-browserstack-service#12]
Hi There,

After updating to the latest browserstack-service 0.1.12 I the execution is slower and I see a lot of instances of this error:

TypeError: feature.getFailureException is not a function
    at BrowserstackService.afterStep (/node_modules/wdio-browserstack-service/build/browserstack-service.js:26:15)

Packages:
    ...
   "wdio-allure-reporter": "^0.1.2",
    "allure-js-commons": "latest",
    "webdriverio-allure-adapter": "^1.0.1",
    "wdio-browserstack-service": "0.1.11",
    "wdio-cucumber-framework": "latest",
    "wdio-cucumber-reporter": "latest",
    "wdio-junit-reporter": "^0.3.0",
    "wdio-selenium-standalone-service": "latest",
    "wdio-spec-reporter": "~0.0.5",
    "webdriverio": "^4.8.0"
    ...

**Comment by itszero** [comment]
😢  the only thing included in 0.1.12 is your patch though. Is it possible for you to produce a minimal cucumber test project so we can debug on this easier?

**Comment by colinrotherham** [comment]
@martino-letgo @itszero The recent pull request https://github.com/itszero/wdio-browserstack-service/pull/11 isn't compatible with Cucumber v2+. If you also update to `wdio-cucumber-framework@1.0.0` or higher, you get the error above.

Here's the code that fails with `feature.getFailureException is not a function` inside **./service/lib/browserstack-service.js**:
```js
  afterStep (feature) {
    if (feature.getFailureException()) {
      ++this.failures
    }
  }
```

Based on info here https://github.com/cucumber/cucumber-js/issues/624#issuecomment-285159099 the check should be:

```js
  afterStep (feature) {
    if (feature.status === 'failed' && feature.failureException) {
      ++this.failures
    }
  }
```

**Comment by radiovisual** [comment]
Yes, I am having the same problem. Launching on BrowserStack with `wdio-browserstack-service@0.1.2`, I get the following errors:

<pre>
TypeError: feature.getFailureException is not a function
at BrowserstackService.afterStep (/Users/mw/gitprojects/tests/node_modules/wdio-browserstack-service/build/browserstack-service.js:26:15)
at execHook (/Users/mw/gitprojects/tests/node_modules/wdio-sync/build/index.js:166:35)
․TypeError: feature.getFailureException is not a function
at BrowserstackService.afterStep (/Users/mw/gitprojects/tests/node_modules/wdio-browserstack-service/build/browserstack-service.js:26:15)
at execHook (/Users/mw/gitprojects/tests/node_modules/wdio-sync/build/index.js:166:35)
․TypeError: feature.getFailureException is not a function
at BrowserstackService.afterStep (/Users/mw/gitprojects/tests/node_modules/wdio-browserstack-service/build/browserstack-service.js:26:15)
at execHook (/Users/mw/gitprojects/tests/node_modules/wdio-sync/build/index.js:166:35)
․TypeError: feature.getFailureException is not a function
at BrowserstackService.afterStep (/Users/mw/gitprojects/tests/node_modules/wdio-browserstack-service/build/browserstack-service.js:26:15)
at execHook (/Users/mw/gitprojects/tests/node_modules/wdio-sync/build/index.js:166:35)
․TypeError: feature.getFailureException is not a function
at BrowserstackService.afterStep (/Users/mw/gitprojects/tests/node_modules/wdio-browserstack-service/build/browserstack-service.js:26:15)
at execHook (/Users/mw/gitprojects/tests/node_modules/wdio-sync/build/index.js:166:35)
․TypeError: feature.getFailureException is not a function
at BrowserstackService.afterStep (/Users/mw/gitprojects/tests/node_modules/wdio-browserstack-service/build/browserstack-service.js:26:15)
at execHook (/Users/mw/gitprojects/tests/node_modules/wdio-sync/build/index.js:166:35)
․TypeError: feature.getFailureException is not a function
at BrowserstackService.afterStep (/Users/mw/gitprojects/tests/node_modules/wdio-browserstack-service/build/browserstack-service.js:26:15)
at execHook (/Users/mw/gitprojects/tests/node_modules/wdio-sync/build/index.js:166:35)
․TypeError: feature.getFailureException is not a function
at BrowserstackService.afterStep (/Users/mw/gitprojects/tests/node_modules/wdio-browserstack-service/build/browserstack-service.js:26:15)
at execHook (/Users/mw/gitprojects/tests/node_modules/wdio-sync/build/index.js:166:35)
</pre>

**Comment by itszero** [comment]
Thanks for the reporting! @colinrotherham do you mind make the change and test it out on your side? I'll be happy to merge it. Thanks!

**Comment by radiovisual** [comment]
I can confirm that the patch suggested by @colinrotherham does seem to fix the problem

**Comment by itszero** [comment]
fix merged. Thanks for everyone's input!

**Comment by itszero** [comment]
0.1.13 released 😄

**Comment by radiovisual** [comment]
Awesome! Thanks @itszero! 🎉  👍
