### ISSUE TITLE
Problem running with webdriver.io version 4.9.2

### ISSUE THREAD

**Issue by ianrenauld** [itszero/wdio-browserstack-service#16]
Tried the latest version of webdriver.io that was released this morning, and it seems to work ok with my tests, except when I try to run over Browserstack, using the wdio-browserstack-service. I get the following message each time (it seems to very briefly start the session on BrowserStack and then quickly errors out with the following):

```
FERROR:
firefox
Error
    at new RuntimeError (/Users/ianrenauld/dev/wdioTest copy/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:144:12)
    at Request._callback (/Users/ianrenauld/dev/wdioTest copy/node_modules/webdriverio/build/lib/utils/RequestHandler.js:301:39)
    at Request.self.callback (/Users/ianrenauld/dev/wdioTest copy/node_modules/webdriverio/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/ianrenauld/dev/wdioTest copy/node_modules/webdriverio/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/ianrenauld/dev/wdioTest copy/node_modules/webdriverio/node_modules/request/request.js:1085:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
ERROR:

Error
    at new RuntimeError (/Users/ianrenauld/dev/wdioTest copy/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:144:12)
    at Request._callback (/Users/ianrenauld/dev/wdioTest copy/node_modules/webdriverio/build/lib/utils/RequestHandler.js:301:39)
    at Request.self.callback (/Users/ianrenauld/dev/wdioTest copy/node_modules/webdriverio/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/ianrenauld/dev/wdioTest copy/node_modules/webdriverio/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/ianrenauld/dev/wdioTest copy/node_modules/webdriverio/node_modules/request/request.js:1085:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by mmitchellgarcia** [comment]
I am also getting the same error with webdriver version 1.0.3. Unfortunately, "ERROR:" is blank in all situations.

`
ERROR:

Error
    at new RuntimeError (/Users/e006707/Projects/test/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:144:12)
    at Request._callback (/Users/e006707/Projects/test/node_modules/webdriverio/build/lib/utils/RequestHandler.js:313:39)
    at Request.self.callback (/Users/e006707/Projects/test/node_modules/request/request.js:186:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/Users/e006707/Projects/test/node_modules/request/request.js:1163:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/Users/e006707/Projects/test/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
`

**Comment by mmitchellgarcia** [comment]
This could be more complex than just the browserstack-service. I dropped a breakpoint and it looks like the successful server response from Browserstack is being treated as an error, even though it is successful.

This is the offending method: https://github.com/webdriverio/webdriverio/blob/master/lib/helpers/utilities.js#L25

![image](https://user-images.githubusercontent.com/3027357/32626857-7ef8fa9e-c55e-11e7-8a69-5319aa08882a.png)

![image](https://user-images.githubusercontent.com/3027357/32626870-90ddd61c-c55e-11e7-85b7-d90841872ccd.png)

It looks like this is a Wdio or Browserstack issue, not wdio-browserstack-service bug.

**Comment by itszero** [comment]
@mmitchellgarcia Thanks for the investigation work! I'll close the ticket here. Please refer to the webdriverio one referenced above if you want to follow-up on the solution!
