### ISSUE TITLE
Failed specs marked as Completed

### ISSUE THREAD

**Issue by NicolasSiver** [itszero/wdio-browserstack-service#4]
I see, that sometimes, a failed spec will be marked as a `Completed` at Browserstack.
Timeout and failed test cases both could be ignored and marked as  `Completed`.

<img width="704" alt="screen shot 2017-04-10 at 4 26 01 pm" src="https://cloud.githubusercontent.com/assets/135263/24881044/91cf9b10-1e0a-11e7-9127-427a6de37d6c.png">

<img width="1018" alt="screen shot 2017-04-10 at 4 26 39 pm" src="https://cloud.githubusercontent.com/assets/135263/24881056/98cbddac-1e0a-11e7-9c23-048492ad72b4.png">

<img width="365" alt="screen shot 2017-04-10 at 4 26 47 pm" src="https://cloud.githubusercontent.com/assets/135263/24881063/9e31775c-1e0a-11e7-89ae-7154513f1041.png">

**Comment by itszero** [comment]
I noticed that sometimes myself too. I'll look into it.

Thanks for the feedback. If you found a fix for it, feel free to submit a PR too!

**Comment by xiankai** [comment]
I found out that this can happen as a result of a failed REST API call to update the Browserstack test results. It seems that by default the test is set as Completed, and in the absence of an update to report the test as failed, results in the scenario shown above.

In my particular scenario, upgrading the Browserstack Jenkins plugin to 1.0.8 resulted in a breaking change that caused the HTTP authentication of the REST API call to fail (https://github.com/jenkinsci/browserstack-integration-plugin/commit/dcea1f40e795dcb466a1ee4e627fd5d04d97b2d1#diff-37f816bf2162bd7883379023b3b38b70R125).

The error I got was:

```
Unhandled rejection StatusCodeError: 401 - "HTTP Basic: Access denied.\n"
    at new StatusCodeError (/Users/kj/spacebib-testing/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/Users/kj/spacebib-testing/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/Users/kj/spacebib-testing/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/Users/kj/spacebib-testing/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/Users/kj/spacebib-testing/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/Users/kj/spacebib-testing/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

Which the error message could be improved on I guess. My solution for now was to downgrade to the 1.0.7 plugin, which sent the API credentials correctly.
